"""Uncertainty, and the circular-versus-oval decision.

The central difficulty is that eccentricity is bounded below by zero. Noise can
only push an estimate *up*, never down, so a perfect circle measured with any
error at all yields a fitted eccentricity greater than zero -- and the shorter
the surviving arc, the larger that spurious value. Reporting "e = 0.31,
therefore oval" would be measuring the digitising noise, not the object.

So the decision is made by comparing models, not by reading a number off a
fit. A five-parameter ellipse is tested against a three-parameter circle, and
the reference distribution is generated by simulating circles that carry *this
object's* arc coverage, point spacing and noise level. Whatever inflation the
short arc causes is then present in the null too, and cancels.

Intervals come from a residual bootstrap rather than resampling points. Points
are resampled in the usual bootstrap, but doing that here would randomly drop
the ends of the arc and so vary the arc coverage between replicates -- changing
the very thing that determines how well eccentricity can be estimated. Holding
the geometry fixed and resampling residuals keeps each replicate an honest
re-run of the same measurement.
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from typing import Dict, Optional, Sequence, Tuple

import numpy as np
from scipy import stats as sps

from .fitting import (
    CircleParams,
    EllipseParams,
    FitError,
    arc_coverage,
    circle_residuals,
    fit_circle,
    fit_circle_batch,
    fit_ellipse,
    fit_ellipse_algebraic,
    fit_ellipse_batch,
    foot_frame,
)

__all__ = [
    "ObjectFit",
    "analyse_points",
    "bca_interval",
    "residual_bootstrap",
    "circularity_test",
    "assign_tier",
    "DEFAULT_TIERS",
    "TierThresholds",
]

_N_ELLIPSE_PARAMS = 5
_N_CIRCLE_PARAMS = 3


# --------------------------------------------------------------------------
# intervals
# --------------------------------------------------------------------------

def bca_interval(boot: np.ndarray, estimate: float, jackknife: np.ndarray,
                 alpha: float = 0.05) -> Tuple[float, float]:
    """Bias-corrected and accelerated bootstrap interval (Efron 1987).

    Falls back to the percentile interval when the correction is undefined --
    which happens when every replicate lands on one side of the estimate, or
    when the jackknife has no spread. A degenerate BCa correction would produce
    an interval that is confidently wrong, so detecting and stepping back from
    it matters more than always returning the fancier interval.
    """
    boot = np.asarray(boot, float)
    boot = boot[np.isfinite(boot)]
    if boot.size < 20:
        return (float("nan"), float("nan"))

    lo_p, hi_p = 100 * alpha / 2, 100 * (1 - alpha / 2)
    percentile = (float(np.percentile(boot, lo_p)), float(np.percentile(boot, hi_p)))

    prop = float(np.mean(boot < estimate))
    if not (0.0 < prop < 1.0):
        return percentile
    z0 = sps.norm.ppf(prop)

    jk = np.asarray(jackknife, float)
    jk = jk[np.isfinite(jk)]
    if jk.size < 3:
        return percentile
    dev = jk.mean() - jk
    denom = 6.0 * (np.sum(dev ** 2) ** 1.5)
    if denom < 1e-300:
        return percentile
    acc = float(np.sum(dev ** 3) / denom)

    out = []
    for z in (sps.norm.ppf(alpha / 2), sps.norm.ppf(1 - alpha / 2)):
        adj = z0 + (z0 + z) / (1.0 - acc * (z0 + z))
        if not np.isfinite(adj):
            return percentile
        out.append(float(np.percentile(boot, 100 * sps.norm.cdf(adj))))
    lo, hi = sorted(out)
    return (lo, hi)


def residual_bootstrap(x: np.ndarray, y: np.ndarray, ell: EllipseParams,
                       n_boot: int, rng: np.random.Generator) -> np.ndarray:
    """Bootstrap ellipse parameters by resampling orthogonal residuals.

    Residuals are inflated by sqrt(n / (n - p)) before resampling. Fitted
    residuals are systematically smaller than the true errors, because the fit
    has already absorbed p degrees of freedom; without the correction the
    intervals come out too narrow.
    """
    frame = foot_frame(ell, x, y)
    foot, normal, resid = frame["foot"], frame["normal"], frame["residual"]
    n = len(resid)
    if n <= _N_ELLIPSE_PARAMS:
        return np.zeros((0, 5))

    infl = np.sqrt(n / (n - _N_ELLIPSE_PARAMS))
    centred = (resid - resid.mean()) * infl

    draws = rng.choice(centred, size=(n_boot, n), replace=True)
    pts = foot[None, :, :] + draws[:, :, None] * normal[None, :, :]
    init = np.repeat(ell.as_array()[None, :], n_boot, axis=0)
    params, _ = fit_ellipse_batch(pts[:, :, 0], pts[:, :, 1], init)
    return params


def _jackknife_params(x: np.ndarray, y: np.ndarray, ell: EllipseParams) -> np.ndarray:
    """Leave-one-out refits, for the BCa acceleration term."""
    n = len(x)
    if n <= _N_ELLIPSE_PARAMS + 1:
        return np.zeros((0, 5))
    keep = ~np.eye(n, dtype=bool)
    xs = np.array([x[k] for k in keep])
    ys = np.array([y[k] for k in keep])
    init = np.repeat(ell.as_array()[None, :], n, axis=0)
    params, _ = fit_ellipse_batch(xs, ys, init)
    return params


def _derived(params: np.ndarray) -> Dict[str, np.ndarray]:
    """Reported quantities from a (B, 5) stack of ellipse parameters."""
    a, b = params[:, 2], params[:, 3]
    with np.errstate(divide="ignore", invalid="ignore"):
        ratio = np.where(a > 0, b / a, np.nan)
        ecc = np.sqrt(np.clip(1.0 - ratio ** 2, 0.0, 1.0))
    return {"major_axis_cm": 2 * a, "minor_axis_cm": 2 * b,
            "eccentricity": ecc, "axis_ratio": ratio}


# --------------------------------------------------------------------------
# the circularity test
# --------------------------------------------------------------------------

def circularity_test(x: np.ndarray, y: np.ndarray, ell: EllipseParams,
                     circ: CircleParams, n_boot: int,
                     rng: np.random.Generator) -> Dict[str, float]:
    """Is the ellipse a better description than a circle?

    Three views of the same comparison:

    * ``p_bootstrap`` -- the headline. Circles are simulated at this object's
      own angular sampling and residual distribution, refitted with an ellipse,
      and the observed eccentricity is placed in that null distribution. This is
      the only one of the three that is immune to short-arc inflation, because
      the null carries the same inflation.
    * ``p_f_test`` -- the classical nested F-test. Reported for readers who
      expect it, but hand-digitised points along a curve are spatially
      autocorrelated, which violates its independence assumption and makes it
      anti-conservative. It should not be led with.
    * ``delta_aicc`` / ``delta_bic`` -- information criteria, positive when the
      ellipse is preferred.
    """
    x = np.asarray(x, float)
    y = np.asarray(y, float)
    n = len(x)

    rss_e = float(np.sum(foot_frame(ell, x, y)["residual"] ** 2))
    r_circ = circle_residuals(circ, x, y)
    rss_c = float(np.sum(r_circ ** 2))

    out: Dict[str, float] = {"rss_ellipse": rss_e, "rss_circle": rss_c}

    # --- F test ---
    df_num = _N_ELLIPSE_PARAMS - _N_CIRCLE_PARAMS
    df_den = n - _N_ELLIPSE_PARAMS
    if df_den > 0 and rss_e > 0:
        f_stat = ((rss_c - rss_e) / df_num) / (rss_e / df_den)
        out["f_stat"] = float(max(f_stat, 0.0))
        out["p_f_test"] = float(sps.f.sf(max(f_stat, 0.0), df_num, df_den))
    else:
        out["f_stat"] = float("nan")
        out["p_f_test"] = float("nan")

    # --- information criteria (Gaussian least squares) ---
    def _aicc(rss: float, k_params: int) -> float:
        k = k_params + 1  # plus the variance
        if rss <= 0 or n - k - 1 <= 0:
            return float("nan")
        aic = n * np.log(rss / n) + 2 * k
        return float(aic + (2 * k * (k + 1)) / (n - k - 1))

    def _bic(rss: float, k_params: int) -> float:
        k = k_params + 1
        if rss <= 0:
            return float("nan")
        return float(n * np.log(rss / n) + k * np.log(n))

    out["delta_aicc"] = _aicc(rss_c, _N_CIRCLE_PARAMS) - _aicc(rss_e, _N_ELLIPSE_PARAMS)
    out["delta_bic"] = _bic(rss_c, _N_CIRCLE_PARAMS) - _bic(rss_e, _N_ELLIPSE_PARAMS)

    # --- parametric bootstrap under a true-circle null ---
    #
    # The null geometry is the fitted circle. Its *noise level* is the awkward
    # part, because it is a nuisance parameter and the two obvious estimates
    # disagree exactly when it matters.
    #
    # Using the circle residuals is the textbook restricted bootstrap and gives
    # essentially exact size, but on a genuinely oval object those residuals are
    # dominated by systematic lack of fit. Feeding that back in as noise widens
    # the null by as much as the signal being tested for, and power collapses.
    # Using the ellipse residuals instead fixes the power but comes out mildly
    # anti-conservative -- the wrong direction here, since a false rejection
    # means calling a circular object oval, the exact error this whole approach
    # exists to avoid.
    #
    # Measured over 300 replicates (2 se = 0.025), nominal size 0.05:
    #
    #                       size 140deg   size 180deg   power(e=.6,150deg)
    #   circle residuals       0.050         0.047            0.45
    #   ellipse residuals      0.073         0.063            1.00
    #   pooled (used here)     0.063         0.063            0.84
    #
    # So the scale is pooled across both estimates while the *shape* of the
    # residual distribution is taken from the ellipse fit, which preserves any
    # non-normality. That keeps size within Monte Carlo error of nominal and
    # recovers most of the power.
    ang = np.arctan2(y - circ.cy, x - circ.cx)
    resid_e = foot_frame(ell, x, y)["residual"]

    var_c = float(np.sum((r_circ - r_circ.mean()) ** 2) / max(n - _N_CIRCLE_PARAMS, 1))
    var_e = float(np.sum((resid_e - resid_e.mean()) ** 2) / max(n - _N_ELLIPSE_PARAMS, 1))
    sigma = np.sqrt(max(0.5 * (var_c + var_e), 0.0))

    resid_c = resid_e - resid_e.mean()
    spread = float(np.std(resid_c))
    resid_c = resid_c / spread * sigma if spread > 1e-12 else resid_c

    draws = rng.choice(resid_c, size=(n_boot, n), replace=True)
    rad = circ.r + draws
    nx = circ.cx + rad * np.cos(ang)[None, :]
    ny = circ.cy + rad * np.sin(ang)[None, :]

    # Seed each null replicate from the circle itself, very slightly
    # non-degenerate so the ellipse fit has a direction to move in.
    seed = np.tile(np.array([circ.cx, circ.cy, circ.r * 1.001, circ.r, 0.0]),
                   (n_boot, 1))
    null_params, _ = fit_ellipse_batch(nx, ny, seed)
    null_e = _derived(null_params)["eccentricity"]
    null_e = null_e[np.isfinite(null_e)]

    obs_e = ell.eccentricity
    if null_e.size >= 20:
        # The +1 keeps the p-value away from exactly zero, which is never
        # justified by a finite number of simulations.
        out["p_bootstrap"] = float((1 + np.sum(null_e >= obs_e)) / (1 + null_e.size))
        out["null_e_median"] = float(np.median(null_e))
        out["null_e_p95"] = float(np.percentile(null_e, 95))
    else:
        out["p_bootstrap"] = float("nan")
        out["null_e_median"] = float("nan")
        out["null_e_p95"] = float("nan")
    return out


# --------------------------------------------------------------------------
# reliability tiers
# --------------------------------------------------------------------------

@dataclass(frozen=True)
class TierThresholds:
    """Cut-offs separating reliable from marginal from indeterminate objects.

    Defaults are placeholders. ``arcfit validate`` recalibrates them from the
    simulation study, and ``arcfit truth`` checks them against the caliper
    measurements, so the published tiers are evidence-based rather than chosen.
    """

    coverage_a: float = 140.0
    coverage_b: float = 100.0
    ci_width_a: float = 0.25
    ci_width_b: float = 0.45
    rms_mm_a: float = 1.0
    rms_mm_b: float = 2.5
    extrapolation_a: float = 1.25
    extrapolation_b: float = 1.60
    size_ci_frac_a: float = 0.20
    size_ci_frac_b: float = 0.50
    calibrated_from: str = "defaults (not yet calibrated)"


DEFAULT_TIERS = TierThresholds()


def assign_tier(coverage_deg: float, ci_width_e: float, rms_mm: float,
                fit_ok: bool, rectified: bool,
                thresholds: TierThresholds = DEFAULT_TIERS,
                extrapolation: float = float("nan"),
                size_ci_frac: float = float("nan")) -> str:
    """Sort an object into tier A (reliable), B (marginal) or C (indeterminate).

    ``extrapolation`` and ``size_ci_frac`` are what catch a runaway fit. A short
    arc on a nearly circular object is badly conditioned: a fraction of a percent
    of calibration error can become several percent of size error, and
    occasionally the fit projects an outline several times larger than anything
    observed. Arc coverage alone does not catch that, because coverage is
    measured against the runaway ellipse and so looks unremarkable.
    """
    if not fit_ok:
        return "C"
    def _v(x, default=np.inf):
        return x if np.isfinite(x) else default
    ci_width_e = _v(ci_width_e)
    rms_mm = _v(rms_mm)
    extrapolation = _v(extrapolation)
    size_ci_frac = _v(size_ci_frac)

    if (rectified and coverage_deg >= thresholds.coverage_a
            and ci_width_e <= thresholds.ci_width_a and rms_mm <= thresholds.rms_mm_a
            and extrapolation <= thresholds.extrapolation_a
            and size_ci_frac <= thresholds.size_ci_frac_a):
        return "A"
    if (coverage_deg >= thresholds.coverage_b
            and ci_width_e <= thresholds.ci_width_b and rms_mm <= thresholds.rms_mm_b
            and extrapolation <= thresholds.extrapolation_b
            and size_ci_frac <= thresholds.size_ci_frac_b):
        return "B"
    return "C"


# --------------------------------------------------------------------------
# the per-object analysis
# --------------------------------------------------------------------------

@dataclass
class ObjectFit:
    """Everything computed for one object."""

    object_id: str = ""
    n_points: int = 0
    fit_ok: bool = False
    error: str = ""

    cx_cm: float = float("nan")
    cy_cm: float = float("nan")
    major_axis_cm: float = float("nan")
    minor_axis_cm: float = float("nan")
    eccentricity: float = float("nan")
    axis_ratio: float = float("nan")
    orientation_deg: float = float("nan")

    major_axis_lo: float = float("nan")
    major_axis_hi: float = float("nan")
    minor_axis_lo: float = float("nan")
    minor_axis_hi: float = float("nan")
    eccentricity_lo: float = float("nan")
    eccentricity_hi: float = float("nan")
    axis_ratio_lo: float = float("nan")
    axis_ratio_hi: float = float("nan")

    coverage_deg: float = float("nan")
    coverage_perimeter_frac: float = float("nan")
    extant_chord_cm: float = float("nan")
    extrapolation_factor: float = float("nan")
    size_ci_frac: float = float("nan")
    rms_residual_mm: float = float("nan")
    max_residual_mm: float = float("nan")

    circle_diameter_cm: float = float("nan")
    p_bootstrap: float = float("nan")
    p_f_test: float = float("nan")
    delta_aicc: float = float("nan")
    delta_bic: float = float("nan")
    null_e_median: float = float("nan")
    null_e_p95: float = float("nan")

    shape_class: str = "indeterminate"
    tier: str = "C"
    n_boot: int = 0
    seed: int = 0

    ellipse: Optional[EllipseParams] = None
    circle: Optional[CircleParams] = None
    boot_params: Optional[np.ndarray] = field(default=None, repr=False)

    def to_row(self) -> dict:
        """Flat dict for the results table (drops the heavy objects)."""
        d = asdict(self)
        for k in ("ellipse", "circle", "boot_params"):
            d.pop(k, None)
        return d


def classify_shape(p_bootstrap: float, ecc_hi: float, alpha: float = 0.05,
                   e_practical: float = 0.5) -> str:
    """Three-way call: elliptical, circular, or indeterminate.

    "Circular" requires more than failing to reject a circle. Failing to reject
    is not evidence of circularity when the data are too weak to have detected
    an ellipse in the first place, so it also requires the interval to *exclude*
    a practically meaningful elongation. Objects that neither reject a circle
    nor rule out a real oval are reported honestly as indeterminate rather than
    being quietly counted as round.

    ``e_practical = 0.5`` corresponds to a minor axis about 87% of the major --
    an elongation that is plainly visible rather than a statistical whisker.
    """
    if not np.isfinite(p_bootstrap):
        return "indeterminate"
    if p_bootstrap < alpha:
        return "elliptical"
    if np.isfinite(ecc_hi) and ecc_hi < e_practical:
        return "circular"
    return "indeterminate"


def analyse_points(x_cm: np.ndarray, y_cm: np.ndarray, object_id: str = "",
                   n_boot: int = 2000, seed: int = 0, alpha: float = 0.05,
                   e_practical: float = 0.5, rectified: bool = True,
                   thresholds: TierThresholds = DEFAULT_TIERS,
                   keep_boot: bool = False) -> ObjectFit:
    """Fit one object and quantify how much the answer can be trusted."""
    x = np.asarray(x_cm, float).ravel()
    y = np.asarray(y_cm, float).ravel()
    out = ObjectFit(object_id=object_id, n_points=len(x), n_boot=n_boot, seed=seed)

    if len(x) < 6:
        out.error = f"need >= 6 points, got {len(x)}"
        return out

    rng = np.random.default_rng(seed)
    try:
        ell = fit_ellipse(x, y)
        circ = fit_circle(x, y)
    except (FitError, np.linalg.LinAlgError) as exc:
        out.error = str(exc)
        return out

    if not np.all(np.isfinite(ell.as_array())) or ell.a <= 0:
        out.error = "ellipse fit did not converge to a valid ellipse"
        return out

    out.fit_ok = True
    out.ellipse, out.circle = ell, circ
    out.cx_cm, out.cy_cm = ell.cx, ell.cy
    out.major_axis_cm = ell.major_axis
    out.minor_axis_cm = ell.minor_axis
    out.eccentricity = ell.eccentricity
    out.axis_ratio = ell.b / ell.a
    out.orientation_deg = float(np.degrees(ell.theta))
    out.circle_diameter_cm = circ.diameter

    resid = foot_frame(ell, x, y)["residual"]
    out.rms_residual_mm = float(np.sqrt(np.mean(resid ** 2)) * 10.0)
    out.max_residual_mm = float(np.max(np.abs(resid)) * 10.0)

    cov = arc_coverage(ell, x, y)
    out.coverage_deg = cov["coverage_deg"]
    out.coverage_perimeter_frac = cov["coverage_perimeter_frac"]

    # The widest separation of the digitised points is a hard lower bound on the
    # reconstructed major axis, and needs no extra measurement to obtain. The
    # ratio between them says how much of the answer is extrapolation: near 1
    # the outline nearly spans the object, while a large value means the fit is
    # projecting far beyond anything actually observed, which is exactly where
    # a short-arc ellipse fit runs away.
    d2 = (x[:, None] - x[None, :]) ** 2 + (y[:, None] - y[None, :]) ** 2
    out.extant_chord_cm = float(np.sqrt(d2.max()))
    if out.extant_chord_cm > 0:
        out.extrapolation_factor = float(out.major_axis_cm / out.extant_chord_cm)

    boot = residual_bootstrap(x, y, ell, n_boot, rng)
    jack = _jackknife_params(x, y, ell)
    if boot.shape[0] >= 20:
        bd = _derived(boot)
        jd = _derived(jack) if jack.shape[0] else {k: np.zeros(0) for k in bd}
        point = {"major_axis_cm": out.major_axis_cm, "minor_axis_cm": out.minor_axis_cm,
                 "eccentricity": out.eccentricity, "axis_ratio": out.axis_ratio}
        for name, attr in (("major_axis_cm", "major_axis"), ("minor_axis_cm", "minor_axis"),
                           ("eccentricity", "eccentricity"), ("axis_ratio", "axis_ratio")):
            lo, hi = bca_interval(bd[name], point[name], jd.get(name, np.zeros(0)), alpha)
            setattr(out, f"{attr}_lo", lo)
            setattr(out, f"{attr}_hi", hi)
        if keep_boot:
            out.boot_params = boot

    test = circularity_test(x, y, ell, circ, n_boot, rng)
    for key in ("p_bootstrap", "p_f_test", "delta_aicc", "delta_bic",
                "null_e_median", "null_e_p95"):
        setattr(out, key, test.get(key, float("nan")))

    out.shape_class = classify_shape(out.p_bootstrap, out.eccentricity_hi,
                                     alpha=alpha, e_practical=e_practical)
    ci_width = out.eccentricity_hi - out.eccentricity_lo
    size_ci_frac = float("nan")
    if np.isfinite(out.major_axis_hi) and np.isfinite(out.major_axis_lo) and out.major_axis_cm > 0:
        size_ci_frac = (out.major_axis_hi - out.major_axis_lo) / out.major_axis_cm
    out.size_ci_frac = size_ci_frac
    out.tier = assign_tier(out.coverage_deg, ci_width, out.rms_residual_mm,
                           out.fit_ok, rectified, thresholds,
                           extrapolation=out.extrapolation_factor,
                           size_ci_frac=size_ci_frac)
    return out
